
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class Ct_StepScan
{

    public short ID { get; set; }

    public string StepName { get; set; }

    public string Description { get; set; }

    public Nullable<short> NumStep { get; set; }

    public string ModelType { get; set; }

}

}
