
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Temp_LogUpload
{

    public int id { get; set; }

    public Nullable<int> SerialNumber { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string FullSTBSN { get; set; }

    public string CASID { get; set; }

    public Nullable<long> SmarCardID { get; set; }

    public Nullable<byte> LineID { get; set; }

    public string StageName { get; set; }

    public Nullable<int> PCBID { get; set; }

}

}
