
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_App_ListForPC
{

    public int ID { get; set; }

    public short App_ID { get; set; }

    public byte LineID { get; set; }

    public short StationID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<short> CT_ScanStep { get; set; }



    public virtual FAS_Applications FAS_Applications { get; set; }

    public virtual FAS_Lines FAS_Lines { get; set; }

}

}
