
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_ShiftsCounter
{

    public int ID { get; set; }

    public short StationID { get; set; }

    public short ID_App { get; set; }

    public byte ShiftID { get; set; }

    public int ShiftCounter { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<int> LOTID { get; set; }

    public Nullable<int> LOT_Counter { get; set; }

    public Nullable<int> PassLOTRes { get; set; }

    public Nullable<int> FAilLOTRes { get; set; }



    public virtual FAS_ShiftsDescription FAS_ShiftsDescription { get; set; }

}

}
