
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Applications
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FAS_Applications()
    {

        this.FAS_App_ListForPC = new HashSet<FAS_App_ListForPC>();

    }


    public short App_ID { get; set; }

    public string App_Name { get; set; }

    public string App_Caption { get; set; }

    public System.DateTime App_CreateDate { get; set; }

    public bool IsActive { get; set; }

    public string App_Path { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAS_App_ListForPC> FAS_App_ListForPC { get; set; }

}

}
