
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_WeightStation
{

    public int SerialNumber { get; set; }

    public short STBWeight { get; set; }

    public System.DateTime WeightDate { get; set; }

    public short WeightByID { get; set; }

    public Nullable<short> Deviation { get; set; }



    public virtual FAS_SerialNumbers FAS_SerialNumbers { get; set; }

}

}
