
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Lines
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FAS_Lines()
    {

        this.FAS_App_ListForPC = new HashSet<FAS_App_ListForPC>();

    }


    public byte LineID { get; set; }

    public string LineName { get; set; }

    public byte TipeID { get; set; }

    public string Print_Line { get; set; }

    public Nullable<byte> Flat_LineID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAS_App_ListForPC> FAS_App_ListForPC { get; set; }

}

}
