
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_MicronSN
{

    public int ID { get; set; }

    public string DevEUI { get; set; }

    public string ShortSN { get; set; }

    public string QR_Code { get; set; }

    public bool Is_Printed { get; set; }

    public Nullable<int> PrintByID { get; set; }

    public Nullable<System.DateTime> PrintDate { get; set; }

    public bool Is_RePrinted { get; set; }

    public Nullable<int> RePrintByID { get; set; }

    public Nullable<System.DateTime> RePrintDate { get; set; }

}

}
