
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_TempSerialNumbers1
{

    public int SerialNumber { get; set; }

    public short LOTID { get; set; }

    public bool IsUsed { get; set; }

    public Nullable<int> PCB_ID { get; set; }

    public Nullable<byte> LineID { get; set; }

    public Nullable<System.DateTime> ManufDate { get; set; }

    public Nullable<short> PrintStationID { get; set; }

}

}
