
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Fixed_RG
{

    public int id { get; set; }

    public int LotID { get; set; }

    public short LitIndex { get; set; }

    public int RGStart { get; set; }

    public int RGEnd { get; set; }

    public System.DateTime LabDate { get; set; }

    public Nullable<int> SN_Count { get; set; }

}

}
