
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Bunch_Decode
{

    public int ID { get; set; }

    public Nullable<int> PCBIDTOP { get; set; }

    public Nullable<int> PCBIDBOT { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> LOTID { get; set; }

    public Nullable<int> FASSNID { get; set; }

}

}
