
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GS_STB
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_UploadSetting
{

    public int ID { get; set; }

    public short ModelID { get; set; }

    public byte Num { get; set; }

    public string Name_Stage { get; set; }

    public short DelaySetting { get; set; }

    public bool CheckStage { get; set; }

}

}
